apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-shop-app
  namespace: coffee-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-shop-app
  template:
    metadata:
      labels:
        app: coffee-shop-app
    spec:
      containers:
      - name: coffee-shop
        image: coffee-shop:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/coffee_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "coffee_user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "coffee_pass"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-shop-service
  namespace: coffee-shop
spec:
  selector:
    app: coffee-shop-app
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
