apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: coffee-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin123"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: coffee-shop
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: coffee-shop
data:
  datasources.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: coffee-shop
data:
  dashboard-provisioning.yml: |
    apiVersion: 1

    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /etc/grafana/provisioning/dashboards
  coffee-shop-dashboard.json: |
    {
      "id": null,
      "title": "Coffee Shop Monitoring Dashboard",
      "tags": ["coffee-shop", "monitoring"],
      "style": "dark",
      "timezone": "browser",
      "panels": [
        {
          "id": 1,
          "title": "Requests Per Second (RPS)",
          "type": "stat",
          "targets": [
            {
              "expr": "sum(rate(http_server_requests_seconds_count[5m]))",
              "refId": "A",
              "legendFormat": "RPS"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "reqps",
              "color": {
                "mode": "palette-classic"
              }
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          }
        },
        {
          "id": 2,
          "title": "Average Response Time",
          "type": "stat",
          "targets": [
            {
              "expr": "sum(rate(http_server_requests_seconds_sum[5m])) / sum(rate(http_server_requests_seconds_count[5m]))",
              "refId": "A",
              "legendFormat": "Avg Response Time"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "s",
              "color": {
                "mode": "palette-classic"
              }
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 0
          }
        },
        {
          "id": 3,
          "title": "Coffee Orders Created",
          "type": "stat",
          "targets": [
            {
              "expr": "coffee_orders_total",
              "refId": "A",
              "legendFormat": "Orders Created"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "short",
              "color": {
                "mode": "palette-classic"
              }
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 8
          }
        },
        {
          "id": 4,
          "title": "Coffee Orders Delivered",
          "type": "stat",
          "targets": [
            {
              "expr": "coffee_orders_delivered_total",
              "refId": "A",
              "legendFormat": "Orders Delivered"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "short",
              "color": {
                "mode": "palette-classic"
              }
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 8
          }
        },
        {
          "id": 5,
          "title": "JVM Memory Used",
          "type": "stat",
          "targets": [
            {
              "expr": "jvm_memory_used_bytes{area=\"heap\"}",
              "refId": "A",
              "legendFormat": "Heap Memory Used"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "bytes",
              "color": {
                "mode": "palette-classic"
              }
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 16
          }
        },
        {
          "id": 6,
          "title": "JVM Memory Non-Heap Used",
          "type": "stat",
          "targets": [
            {
              "expr": "jvm_memory_used_bytes{area=\"nonheap\"}",
              "refId": "A",
              "legendFormat": "Non-Heap Memory Used"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "bytes",
              "color": {
                "mode": "palette-classic"
              }
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 16
          }
        },
        {
          "id": 7,
          "title": "RPS Over Time",
          "type": "timeseries",
          "targets": [
            {
              "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
              "refId": "A",
              "legendFormat": "RPS"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "reqps",
              "color": {
                "mode": "palette-classic"
              }
            }
          },
          "gridPos": {
            "h": 8,
            "w": 24,
            "x": 0,
            "y": 24
          }
        },
        {
          "id": 8,
          "title": "Response Time Over Time",
          "type": "timeseries",
          "targets": [
            {
              "expr": "sum(rate(http_server_requests_seconds_sum[5m])) / sum(rate(http_server_requests_seconds_count[5m]))",
              "refId": "A",
              "legendFormat": "Average Response Time"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "s",
              "color": {
                "mode": "palette-classic"
              }
            }
          },
          "gridPos": {
            "h": 8,
            "w": 24,
            "x": 0,
            "y": 32
          }
        },
        {
          "id": 9,
          "title": "Orders Created Over Time",
          "type": "timeseries",
          "targets": [
            {
              "expr": "coffee_orders_total",
              "refId": "A",
              "legendFormat": "Orders Created"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "short",
              "color": {
                "mode": "palette-classic"
              }
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 40
          }
        },
        {
          "id": 10,
          "title": "Orders Delivered Over Time",
          "type": "timeseries",
          "targets": [
            {
              "expr": "coffee_orders_delivered_total",
              "refId": "A",
              "legendFormat": "Orders Delivered"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "short",
              "color": {
                "mode": "palette-classic"
              }
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 40
          }
        },
        {
          "id": 11,
          "title": "JVM Memory Usage Over Time",
          "type": "timeseries",
          "targets": [
            {
              "expr": "jvm_memory_used_bytes{area=\"heap\"}",
              "refId": "A",
              "legendFormat": "Heap Memory"
            },
            {
              "expr": "jvm_memory_used_bytes{area=\"nonheap\"}",
              "refId": "B",
              "legendFormat": "Non-Heap Memory"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "bytes",
              "color": {
                "mode": "palette-classic"
              }
            }
          },
          "gridPos": {
            "h": 8,
            "w": 24,
            "x": 0,
            "y": 48
          }
        }
      ],
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "refresh": "5s"
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: coffee-shop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
